# Generated by Django 4.2.5 on 2023-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6'), ('S7', 'Semester 7'), ('S8', 'Semester 8')], max_length=2)),
                ('question', models.TextField()),
            ],
        ),
    ]
