# Generated by Django 4.2.5 on 2023-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='semester',
        ),
        migrations.AddField(
            model_name='registration',
            name='branches',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ME', 'Mechanical Engineering')], default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='registration',
            name='semesters',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6'), ('S7', 'Semester 7'), ('S8', 'Semester 8')], default='S1', max_length=2),
        ),
    ]
